 version: 2.1

 orbs:
  win: circleci/windows@2.2.0
  discord: antonioned/discord@0.1.0


 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run:
                 command: |
                   mkdir /tmp/artifacts 
                   dotnet build ./source/Engine.csproj -o /tmp/artifacts
       - store_artifacts:
          path: /tmp/artifacts
       - discord/status:
          fail_only: false
          failure_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
          webhook: "${DISCORD_STATUS_WEBHOOK}"
          success_message: "**${CIRCLE_USERNAME}**'s build: **${CIRCLE_JOB}** failed."
         